import { useState, useEffect } from "react";
import Head from "next/head"
import { Box, Stack, Text, Select, Container, Button, Modal, ModalCloseButton, ModalContent, ModalOverlay, ModalHeader, ModalBody, Flex } from "@chakra-ui/react";
import FullCalendar from '@fullcalendar/react';
import dayGridPlugin from '@fullcalendar/daygrid';
import interactionPlugin from "@fullcalendar/interaction"

export default function Client() {
  const [selectedOption, setSelectedOption] = useState("");
  const [selectedDate, setSelectedDate] = useState("")
  const [isOpen, setIsOpen] = useState(false);

  useEffect(() => {
    
  }, []);

  const handleClose = () => {
    setSelectedDate(null);
    setIsOpen(false);
    console.log("modal close")
  };

  const handleDayClick = (arg) => {
    console.log("Day clicked:", arg.dateStr);
    setIsOpen(true);
  };

  const [events, setEvents] = useState([{
    title: 'Booked',
    start: new Date(2024, 1, 27), // Year, Month (0-11), Day, Hour, Minute
    end: new Date(2024, 1, 28,),
  },
  {
    title: 'Booked',
    start: new Date(2024, 1, 28, 13, 0),
    end: new Date(2024, 1, 28, 15, 0),
  }]);

  
  const handleRoomSelect = (event) => {
    setSelectedOption(event.target.value);

    console.log(event.target.value)

    if(event.target.value === ""){
      setEvents([])
    }else {
      setEvents([
        {
          title: `Event ${selectedOption}`,
          start: new Date(2024, 1, 23), // Year, Month (0-11), Day, Hour, Minute
          end: new Date(2024, 1, 27),
        }
      ])
    }
  }

  return (
    <>
      <Head>
        <title>Client</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW='700px'>
        <Modal isOpen={isOpen} onClose={handleClose} size='sm'>
          <ModalOverlay />
          <ModalContent>
            <ModalHeader>Testing</ModalHeader>
            <ModalBody p={4}>
              <Flex direction='row' gap={4}>
                <Button disabled colorScheme='blue'>Book Now!</Button>
                <Button onClick={handleClose}>Close</Button>
              </Flex>
            </ModalBody>
          </ModalContent>
        </Modal>

        <Stack direction='column' flex='1'>
          <Text>Select Room: </Text>
          <Box>
            <Select value={selectedOption} onChange={handleRoomSelect} placeholder="Select Room">
              <option value='room-101'>Room 101</option>
              <option value='room-102'>Room 102</option>
            </Select>
          </Box>
          <Text>Available Dates: </Text>
          <Box>
            <FullCalendar
              height='500px'
              plugins={[ dayGridPlugin, interactionPlugin  ]}
              initialView="dayGridMonth"
              events={events}
              selectable={true}
              dateClick={handleDayClick}
            />
            {/* <Calendar 
              localizer={localizer}
              events={events}
              views={['month']}
              startAccessor="start"
              endAccessor="end"
              selectable={true}
              // onSelectSlot={handleSlotSelect}
              dayPropGetter={dayPropGetter}
            /> */}
          </Box>
        </Stack>
      </Container>
    </>
  )
}